name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r OTU_predictor.egg-info/requires.txt

    - name: Install package
      run: |
        pip install .

    - name: Test import
      run: |
        python -c "import OTU_predictor"

    - name: Run tests (replace with your actual test command)
      run: |
        python -m unittest discover

    - name: Cleanup
      run: |
        pip uninstall -y OTU-predictor
